---
- name: Install common packages for Fedora Linux
  hosts: fedora_servers
  become: true
  vars_files:
    - ../vault/vault.yml
  tasks:
    - name: Install packages
      dnf:
        name:
          - neofetch
          - htop
          - vim
          - git
          - zsh
          - wget
          - curl
          - screen
          - tmux
        state: latest

- name: Install common packages for Debian Linux
  hosts: debian_servers
  become: true
  vars_files:
    - ../vault/vault.yml
  tasks:
    - name: Install packages
      apt:
        name:
          - neofetch
          - htop
          - vim
          - git
          - zsh
          - wget
          - curl
          - screen
          - tmux
        state: latest
